### ISSUE TITLE
Suggestion related to custom dimensions & tracking

### ISSUE THREAD

**Issue by iniznet** [deconf/Analytics-Insights#1]
I can't find the enhancement link so I posted it here. I currently using the plugin with GTM tracking because I can't add a few custom dimensions that I want in the settings and need to create another analytic reporting v4 script to pull the data, and it's really inconvenient to do for every site we want to set up.

So it would be great for developer if we were able to insert what custom dimensions we want into the settings and have a function to be able to pull the stats data from it with time range support as an array.

**Comment by iniznet** [comment]
After thinking about it, we can ignore the "custom dimensions we want into the settings" part as it's set to the analytic tag in GTM, but would be great to have a function to be able to pull the stats data from a custom dimension with time range support as an array.

**Comment by deconf** [comment]
Is too risky for the API Project, since it could generate a high rate of error if the user configures an unsupported dimension or a wrong combination of dimensions and metrics.
