### ISSUE TITLE
Ga4 was disconnected dont have statistics from 3.00 AM 

### ISSUE THREAD

**Issue by nemis2017** [deconf/Analytics-Insights#10]
this is error in report & error:

Count: 0
Ajax Error Code: 624
API Error Code: None
API Error Reason: 
None
API Error Details: 
None

**Comment by deconf** [comment]
Hi,

The reports are delayed on GA4, is there a difference between the Google Analytics reports and the plugin?

**Comment by deconf** [comment]
This was fixed on latest update, also check https://support.google.com/analytics/answer/1070983?hl=en#zippy=%2Cin-this-article
