### ISSUE TITLE
This report is unavailable (621)  with data for today

### ISSUE THREAD

**Issue by Robin-Andrews** [deconf/Analytics-Insights#11]
This report is unavailable (621) appears frequently when I try to access data for today, even when data is available for yesterday or the last 7 days. This has only started happening in the last few weeks.

**Comment by deconf** [comment]
Hi,

"This report is unavailable (621)" is not an error, it simply means Google Analytics hasn't yet processed the report for that timeframe. Please note that in Google Analytics 4 it takes up to 48 hour for report data to be processed.

**Comment by deconf** [comment]
Closing this issue since this isn't an error, it's how Google Analytics 4 works.

More details here: 
 https://support.google.com/analytics/answer/1070983?hl=en#zippy=%2Cin-this-article
